# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "proto/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=google

  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        args:
          - --style=google
          - --parallel
          - --in-place
        additional_dependencies: [toml]
