[tool.poetry]
name = "sync-crawler"
version = "0.1.0"
description = ""
authors = ["David Chiu <david20571015@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
protobuf = "^4.24.3"
lmdb = "^1.4.1"
typing-extensions = "^4.8.0"


[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
pylint = "^3.0.0"
yapf = "^0.40.2"

[tool.yapf]
based_on_style = "google"

[tool.isort]
profile = "google"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
